# DQN CartPole

In [1]:
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import random

### Ortamı Tanımlama

In [2]:
env = gym.make('CartPole-v1') # CartPole ortamını tanımlar

In [4]:
env.reset()
action = env.action_space.sample() # eylem uzayından rastgele eylem seçilir
result = env.step(action) # eylem gerçekleştirilir ve sonuç alınır
print(result)

(array([ 0.04079386, -0.18728113, -0.01661446,  0.31521043], dtype=float32), 1.0, False, False, {})


In [5]:
state, reward, done = result[:3] 
# state, reward, done, _, _ = result 
print(state, reward, done)

[ 0.04079386 -0.18728113 -0.01661446  0.31521043] 1.0 False


In [6]:
#Ajan eğitilmediğinde bu şekilde çalışır
env.reset()
while True:
    #env.render() CartPole ortamı için render çalışmıyor
    action = env.action_space.sample()
    state, reward, done = env.step(action)[:3]
    print(state, reward, done)
    if done: # bölümün bitimini gerçekleştirme
        env.close()
        break

[-0.01694924 -0.19549517 -0.02947601  0.27168965] 1.0 False
[-0.02085914 -0.39018437 -0.02404222  0.55493194] 1.0 False
[-0.02866283 -0.58496064 -0.01294358  0.8399442 ] 1.0 False
[-0.04036204 -0.38966438  0.00385531  0.54321903] 1.0 False
[-0.04815533 -0.19459684  0.01471969  0.2517533 ] 1.0 False
[-0.05204727  0.00031186  0.01975475 -0.03625064] 1.0 False
[-0.05204103 -0.19508772  0.01902974  0.26259905] 1.0 False
[-0.05594278 -0.0002425   0.02428172 -0.02402144] 1.0 False
[-0.05594763  0.19452296  0.02380129 -0.3089454 ] 1.0 False
[-0.05205717 -0.00092989  0.01762238 -0.00885224] 1.0 False
[-0.05207577  0.19393496  0.01744534 -0.2959234 ] 1.0 False
[-0.04819707 -0.00143129  0.01152687  0.00221004] 1.0 False
[-0.0482257   0.19352347  0.01157107 -0.28681386] 1.0 False
[-0.04435523  0.38847852  0.00583479 -0.57582504] 1.0 False
[-0.03658566  0.5835182  -0.00568171 -0.8666641 ] 1.0 False
[-0.02491529  0.778717   -0.02301499 -1.161128  ] 1.0 False
[-0.00934095  0.97413105 -0.04623755 -1.